### ISSUE TITLE
Crash running OrthoMCL

### ISSUE THREAD

**Issue by chatcrawler** [ODoSE/odose.nl#2]
To whom it may concern.

I have uploaded multi-fasta-files (in*.ffn-format) that each contain the nucleotide sequences present in a small syntenic region of the whole genomes of 22 natural isolates. After flawlessly progressing for around three days, there was a critical OrthoMCL-step failure. Find the error message below. Thanks for your support in advance! With kind regards

Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A60 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A60.dataset_32617.dat.formatted_bSiPLl.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A51 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A51.dataset_32614.dat.formatted_jUrkRX.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A56 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A56.dataset_32615.dat.formatted_ZRq4qQ.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A58 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A58.dataset_32616.dat.formatted_J9G9Yi.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A93 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A93.dataset_32622.dat.formatted_ReB0qr.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A92 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A92.dataset_32621.dat.formatted_Pri3OB.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A15 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A15.dataset_32604.dat.formatted_bFRd1h.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A32 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A32.dataset_32608.dat.formatted_ysdJa3.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A31 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A31.dataset_32607.dat.formatted_n1cFfD.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A30 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A30.dataset_32606.dat.formatted_5g8_lM.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A34 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A34.dataset_32609.dat.formatted_Eo76t4.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A39 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A39.dataset_32610.dat.formatted_SE2sh2.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A72 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A72.dataset_32620.dat.formatted_PJCQfM.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A46 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A46.dataset_32612.dat.formatted_qmZGJb.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A44 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A44.dataset_32611.dat.formatted_GrWmYR.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A49 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A49.dataset_32613.dat.formatted_UiCNnj.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A26 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A26.dataset_32605.dat.formatted_0gyIut.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A64 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A64.dataset_32619.dat.formatted_GLNsqm.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A00 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A00.dataset_32601.dat.formatted_Yguufv.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A06 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A06.dataset_32602.dat.formatted_Kmm6cm.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A07 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A07.dataset_32603.dat.formatted_IiwotN.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclAdjustFasta A62 /work/odosenl/galaxy-dist/database/tmp/orthomcl_proteins_IRhYuO/A62.dataset_32618.dat.formatted_as0tn6.ffn 3
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclFilterFasta /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta 30 20
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/makeblastdb -in /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/filtered_fasta/good_proteins.fasta -dbtype prot -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/my_prot_blast_db
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A60.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A60-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A51.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A51-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A56.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A56-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A58.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A58-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A93.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A93-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A92.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A92-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A15.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A15-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A32.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A32-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A31.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A31-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A30.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A30-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A34.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A34-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A39.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A39-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A72.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A72-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A46.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A46-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A44.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A44-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A49.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A49-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A26.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A26-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A64.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A64-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A00.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A00-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A06.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A06-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A07.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A07-vs-all.tsv
Executing: /work/odosenl/software/ncbi-blast-2.2.30+/bin/blastp -db my_prot_blast_db -query /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta/A62.fasta -outfmt 6 -out /work/odosenl/galaxy-dist/database/tmp/reciprocal_blast__eK3WQ/blast/A62-vs-all.tsv
Executing: /work/odosenl/software/orthomclSoftware-v2.0.9/bin/orthomclBlastParser /work/odosenl/galaxy-dist/database/tmp/all-vs-all_GJcq7M.tsv /work/odosenl/galaxy-dist/database/tmp/orthomcl_run_4I1sm2/compliant_fasta
<class '_mysql_exceptions.OperationalError'>
Failed to send email: OperationalError @ /usr/lib/python2.7/dist-packages/MySQLdb/connections.py:__init__
Automatic bug submission reported: OperationalError @ /usr/lib/python2.7/dist-packages/MySQLdb/connections.py:__init__
An error occurred
Traceback (most recent call last):
  File "/work/odosenl/galaxy-dist/tools/odosenl/wrapper.py", line 32, in <module>
    MODULE.main(sys.argv[3:])
  File "/work/odosenl/odose.nl/run_orthomcl.py", line 451, in main
    run_orthomcl(args, proteome_files)
  File "/work/odosenl/odose.nl/run_orthomcl.py", line 80, in run_orthomcl

**Comment by timtebeek** [comment]
Just a quick note to let you know I'm looking into this. The Mysql database server appears not to be available at the moment, so I've contacted @harmn to hopefully get this resolved quickly.

**Comment by chatcrawler** [comment]
Thanks for your quick note, Tim.

It appears I already experienced this mysql issue two years ago, when ODOSE has been just released.

Let me know when the mysql would be up and running again!

Cheers

Séb

**Comment by timtebeek** [comment]
Hi Séb, the orthomcl database issues should now be fixed again! If you have any other issues please let me know, although I should be receiving automatic bug reports again..
