### ISSUE TITLE
license

### ISSUE THREAD

**Issue by bgruening** [ODoSE/odose.nl#5]
Hi, 

under which license is odose released?

Thanks!
Bjoern

**Comment by timtebeek** [comment]
Hi @bgruening ; Just applied the MIT license to it, so it should be free to reuse / redistribute.
Thanks!

**Comment by bgruening** [comment]
Cool thanks, we need this for the conda package. Slowly catching up ... :)

**Comment by timtebeek** [comment]
Awesome! Anywhere I can follow along / help out where possible?
